#!/bin/sh

[ -d /root/app ] || exit 0

start() {
	printf "Starting APP: "

	if [ -d /root/app ]; then
        	if [ -f /root/app/start.sh ]; then
  			chmod +x /root/app/start.sh
  			cd /root/app
  			/root/app/start.sh
		fi
	fi
}

stop() {
	printf "Shutting down APP: "
        if [ -d /root/app ]; then
                if [ -f /root/app/stop.sh ]; then
                        chmod +x /root/app/stop.sh
                        cd /root/app
                        /root/app/stop.sh
                fi
        fi
}

restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?
